name: test

on:
    push:
        branches:
          - develop

    pull_request:
        branches:
          - develop

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

jobs:
    test:
        runs-on: [ubuntu-latest]
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Versions
            run: |
                swift --version
          - name: Swift Test
            run: |
                swift test
